services:
  - type: web
    name: ds-churn-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: ds-churn-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
